### ISSUE TITLE
Crash if RSS feed is not available

### ISSUE THREAD

**Issue by saldous** [nmdias/FeedKit#13] opened 2017-02-15 03:55 UTC
I was using the feed from: http://feeds.washingtonpost.com/rss/politics and all was fine, until today when the Washington Post's feed went offline. FeedKit crashes in the guard let statement for some reason, it isn't handling the error correctly.

I can reproduce this in your example project too by replacing the feedURL in FeedTableViewController.swift with the above Washington Post URL.

<img width="780" alt="screen shot 2017-02-14 at 10 54 36 pm" src="https://cloud.githubusercontent.com/assets/3334306/22960000/a15f9030-f308-11e6-9ad4-98d88477821a.png">

**Comment by nmdias** [comment] 2017-02-15 08:37
@saldous this seems to be a duplicate of issue #4 

Can you check it out? And if so, can you try and replicate the radar submitted there to see if I can get more people to submit this bug to Apple?

There's also a [workaround](https://github.com/nmdias/FeedKit/issues/4#issuecomment-255531127).

Thanks

**Comment by saldous** [comment] 2017-02-15 12:59
Hi @nmdias, thanks, that workaround fixes the issue.

**Closed** 2017-02-15 13:08 UTC
Labels: duplicate
